// Generates the bonus (remix) puzzle for every stage that has a bonus branch
// on the map: same drawing as the stage, harder unique-solution puzzle (see
// bonus-core.js). Each result is cached in tools/out/bonus/ together with its
// source stage's edges; www/bonus.js is then rewritten from the cached results
// that still match the current stages (keyed by stage index).
//
// usage:
//   node tools/gen-bonus.js            all bonus stages
//   node tools/gen-bonus.js 8 16       only these stage numbers (1-based)
//   node tools/gen-bonus.js --write    only rewrite www/bonus.js from the cache

const fs = require("fs");
const path = require("path");
const { makeBonus } = require("./bonus-core.js");

const OUT_DIR = path.join(__dirname, "out", "bonus");
const PRESETS = path.join(__dirname, "..", "www", "presets.js");

const sigOf = (level) => JSON.stringify(level.edges);

// The game's VISIT_ALL stage list.
function loadStages() {
  const window = {};
  new Function("window", fs.readFileSync(PRESETS, "utf8"))(window);
  return window.PRESETS_ALL;
}

async function main() {
  const { hasBonus } = await import("../www/level-graph.js");
  const stages = loadStages();
  const total = stages.length;
  const args = process.argv.slice(2);
  const wanted = args.filter((a) => a !== "--write").map(Number);
  const targets = args.includes("--write") ? [] : wanted.length ? wanted.map((x) => x - 1) : stages.map((_, i) => i).filter((i) => hasBonus(i, total));
  fs.mkdirSync(OUT_DIR, { recursive: true });
  for (const i of targets) {
    const src = { ...stages[i] };
    delete src.bonus;
    let best = null;
    // Small stages are cheap to search, so try more seeds there.
    const seeds = Object.keys(src.vertices).length <= 14 ? 10 : 3;
    for (let seed = 1; seed <= seeds; seed++) {
      const b = makeBonus(src, { seed: seed * 100 + i, iters: 600, starts: 99 });
      if (b && (!best || b.stats.difficulty > best.stats.difficulty)) best = b;
    }
    if (!best) { console.log(`stage ${i + 1}: no bonus found`); continue; }
    fs.writeFileSync(path.join(OUT_DIR, `stage-${i + 1}.json`), JSON.stringify({ sourceSig: sigOf(src), level: best.level, stats: best.stats }));
    console.log(`stage ${i + 1}: ${JSON.stringify(best.stats)}${best.stats.difficulty <= best.stats.baseDifficulty ? "  WARNING: not harder than the stage" : ""}`);
  }

  // Rewrite www/bonus.js from every cached result whose source still matches.
  const bonus = {};
  stages.forEach((st, i) => {
    const f = path.join(OUT_DIR, `stage-${i + 1}.json`);
    if (!hasBonus(i, total) || !fs.existsSync(f)) return;
    const cached = JSON.parse(fs.readFileSync(f, "utf8"));
    if (cached.sourceSig === sigOf(st)) bonus[i] = { ...cached.level, sourceName: st.name };
  });
  fs.writeFileSync(path.join(__dirname, "..", "www", "bonus.js"),
    "// Generated by tools/gen-bonus.js: bonus puzzle per stage index (same drawing, harder puzzle).\n" +
    "window.BONUS_ALL = " + JSON.stringify(bonus) + ";\n");
  console.log(`wrote www/bonus.js (stages ${Object.keys(bonus).map((i) => Number(i) + 1).join(", ")})`);
}

main();
